language: android
android:
  components:
    - tools
    - platform-tools
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
   - cd PopularMoview && ./gradlew assembleDebug
