language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

licenses:
    - android-sdk-license-.+
    - '.+'

script:
   - cd PopularMovies && ./gradlew assembleDebug

jdk:
  - oraclejdk8

notifications:
  slack: felipecpc:fPwiCIB0IGY2bSxCqiGsWhlD
