language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
   - cd PopularMovies && ./gradlew assembleDebug

jdk:
  - oraclejdk8
